### ISSUE TITLE
HALP, MANY OF US CAN'T ACCESS GITTER!!!!

### ISSUE THREAD

**Issue by jabrank2** [githubteacher/sep-27-developers#20]
Firewall in the office is getting in the way. Any other way to chat??

**Comment by brianamarie** [comment]
@jabrank2 I will answer questions, feel free to open issues in this repository with anything. 😄

**Comment by brianamarie** [comment]
I'm going to close this now, please feel free to open new issues for questions.

**Comment by jabrank2** [comment]
Awesome, thanks!
