### ISSUE TITLE
Failed to connect to github.com port 443: Timed out

### ISSUE THREAD

**Issue by jabrank2** [githubteacher/sep-27-developers#46]

**Comment by brianamarie** [comment]
@jabrank2 You mentioned you are a behind a firewall...this may be an issue with communicating with GitHub.com. Do you have a proxy that you are aware of?

**Comment by jabrank2** [comment]
Yes, worked all break to get around it....am good now! :smile:

**Comment by brianamarie** [comment]
Great! 🎉
