### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by ghost** [githubteacher/sep-27-developers#47]
@githubteacher  Gitter is blocked by my company's firewall so I can't ask questions there.  

We just start using the enterprise version of Github at my company. 

It would be great to do a similar training with our team members. Would it be possible for you to add the script you are using to auto add users (or anything else that comes up) to the repo (minus any security tokens, etc)?

**Comment by brianamarie** [comment]
@jlfabi Hello! 👋 

I'm not sure I understand the question. Are you asking about using the script for a different repository? If so, totally possible - the script is open source and [found here](https://github.com/github/training-utils).

We also do training on-site as a GitHub Professional Services team. Would it be OK if I gave your information to our operations team so we could explore that option? 

cc/ @jordanmccullough

**Comment by ghost** [comment]
That is what I was looking for, thanks. 

Yes, you can give them my information.  I am using my personal GitHub account for this training. Please have them contact my via email, jfabi@travelers.com

**Comment by brianamarie** [comment]
Great! I'll pass along your information. 😄
