### ISSUE TITLE
Going too fast

### ISSUE THREAD

**Issue by jabrank2** [githubteacher/sep-27-developers#48]

**Comment by jabrank2** [comment]
Not able to create a branch

**Comment by brianamarie** [comment]
@jabrank2 What is the output when you try to commit locally?

**Comment by jabrank2** [comment]
Not a valid object name: 'master'

**Comment by brianamarie** [comment]
Ok. Are you inside the directory of the cloned repository? If so, what happens when you type `git branch`?

**Comment by jabrank2** [comment]
I am in the U:\test\Sep-27-developers directory. git branch command gives me nothing

**Comment by brianamarie** [comment]
Ok. What about if you type `git --version`?

**Comment by jabrank2** [comment]
2.7.1.windows.2

**Comment by brianamarie** [comment]
Okay. Which CLI application are you using?

**Comment by jabrank2** [comment]
Git CMD

**Comment by brianamarie** [comment]
Ah! Do you have `Git Bash` installed?

**Comment by jabrank2** [comment]
yup

**Comment by jabrank2** [comment]
I am in the $ directory in Bash now

**Comment by brianamarie** [comment]
Ok. I suggest trying the same commands in `git bash`.

**Comment by jabrank2** [comment]
ok, trying now...thanks!

**Comment by brianamarie** [comment]
Let me know how it goes! 😄

**Comment by jabrank2** [comment]
Not going well. 5 of us are logged in from work, if we get stuck on one thing, we miss 5 more topics!

**Comment by jabrank2** [comment]
Branch command fails. Getting "fatal: Not a git repository (or any of the parent repositories): .git

**Comment by brianamarie** [comment]
😢  So sorry to hear this. We will help get you caught up during the break, and we will also send out the recording of the session.

**Comment by brianamarie** [comment]
> Branch command fails. Getting "fatal: Not a git repository (or any of the parent repositories): .git

@jabrank2 Are you still in your directory that you cloned earlier?

**Comment by jabrank2** [comment]
No I made another \test folder inside it
\test\test is where I am

**Comment by brianamarie** [comment]
Ah, that's probably the issue. Navigate to the git repository you cloned, then let's try again. I believe that was `\test\sep-27-developers`, right?

**Comment by jabrank2** [comment]
aha! let me try that

**Comment by jabrank2** [comment]
It seems to go through and create the branch this time. If I could only have the remaining list of commands I needed to run after...

**Comment by brianamarie** [comment]
Hold tight...

**Comment by brianamarie** [comment]
- `git branch BRANCH-NAME`
- `git checkout BRANCH-NAME`
- Create a file named `USERNAME-HOMETOWN.md` using your favorite text editor.
- Fill in some basic information to start the document.
- Add the document to the staging area: `git add USERNAME-HOMETOWN.md`
- Commit the file to history: `git commit -m 'commit message'`
- Push the file up to the remote repository: `git push -u origin BRANCH-NAME`

**Comment by jabrank2** [comment]
THANK YOU! :+1:

**Comment by brianamarie** [comment]
I'm going to close this issue for now - please feel free to reopen or to open a new one. 😄
