### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by ghost** [githubteacher/sep-27-developers#49]
@githubteacher   I am blocked by my company from committing my branch.

**Comment by brianamarie** [comment]
@jlfabi I'm sorry to hear that. Do you know of any proxies you may be able to use?

**Comment by ghost** [comment]
Used hot spot on my phone.

**Comment by brianamarie** [comment]
Great workaround, @jlfabi! I'm going to close this issue, but please re-open or open a new one with more questions. 😄
